// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventProto.proto

package song.mingu.proto;

public interface EventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:song.mingu.event.EventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sourceId = 1;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <code>string sourceId = 1;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string eventId = 2;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 2;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();
}
