// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventProto.proto

package song.mingu.proto;

public interface EventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:song.mingu.event.EventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
